name: tquestion_tag_app
description: "A Flutter application for learning Tag Question."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Fonts & Animations
  google_fonts: ^6.1.0
  lottie: ^3.1.0

  # Storage & State Management
  shared_preferences: ^2.1.0
  provider: ^6.1.1

  # UI Animations Package
  animations: ^2.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
